### ISSUE TITLE
layout/overflow issue in suggestion-list

### ISSUE THREAD

**Issue by braver** [atom-community/autocomplete-plus#194]
Commit 3985780f7fb708582f2b9df41b10b932ba0ee2e6 puts `overflow: visible` on the `list-group`. This makes the items overflow out of the box that is max 200px high. The commit seems to solve a problem, but it's a bit messy and causes [a problem](https://github.com/braver/isotope-ui/issues/7) in isotope-ui where the suggestion box is not expanding.

I see two possible solutions:

1. set overflow back to auto
2. or if the list should grow, remove the max-height by setting `max-height: none` on the list-group

![screen shot 2015-01-15 at 09 23 15](https://cloud.githubusercontent.com/assets/2543659/5754496/f1a64c4a-9c99-11e4-8691-6d7aaf00e9a1.png)

**Comment by joefitzgerald** [comment]
This makes sense, and should be fixed. I think I made this change because the list was not expanding to display suggestions up to max-suggestions (assuming there is enough room to display them) and was instead requiring a scroll to show them. I think my preference would be for # 2 above - any reason why # 1 would be preferable?

**Comment by braver** [comment]
No, option 1 doesn't make much sense if you're already limiting the number of items in the list programmatically. The 200px max-height seems quite arbitrary. 

In fact, I think I'm going to put in a pull request to make `.select-list.popover-list ol.list-group` use 'max-height: 50vh' or some other viewport-related value. I think it makes sense and would also mean you wouldn't have to change anything from the default popover-list.
