### ISSUE TITLE
requestHandler doesn't get called when typing a " "

### ISSUE THREAD

**Issue by acormier** [atom-community/autocomplete-plus#268]
Hi @benogle, 
@joefitzgerald said I should send this one your way.

requestHandler should be called when a " " is typed.

ex scenario:
If a "." or a " " is typed a new list of suggestions is fetched from another process which is cache and as the user continues to type the list is filtered based on the prefix.

**Comment by joefitzgerald** [comment]
@benogle what are your thoughts on this? I know you had an opinion on triggering on backspace. I can see how triggering on space could be useful. @acormier uses the example of:

`using<spacehere>` he would like to show a list of namespaces that someone could choose, which I think is a valid scenario.

Similarly, I could write a provider for golang that would provide imports suggestions on `import<spacehere`.

This is offset by my thoughts that a carriage return should not trigger autocomplete. What do you think of this:

* Addition / removal of whitespace on a single line should be allowed to trigger activation
* Insertion / deletion of carriage return / line feed should not be allowed to trigger activation
* Insertion / deletion of tab should not be allowed to trigger activation
* `Any other rules here?`

This would imply removing the `trim()` we currently do on newText and oldText and doing something a little more nuanced. Thoughts?

**Comment by underscorediscovery** [comment]
This is key for even the basics, like `function( hello,<space>NOPE`  
+1!

**Comment by underscorediscovery** [comment]
(On 2.6.0 - this seems to be resolved and or much better, quick tests).

**Comment by benogle** [comment]
@underscorediscovery do you expect the default provider to show on space? Or your own custom provider? I disagree with the former, and agree with the ability for the latter.

**Comment by underscorediscovery** [comment]
I think it will vary by language, but `,` `space/s` and `(` `space/s` are common and frustrating to use without them. You can't type an argument list without crunching them with no spaces, because the completion just keeps getting pulled away. 

I don't see a benefit in that in any provider, but I can see how on a blank line (say when using spaces as tabs) it would be a bit weird to pop up constantly. For custom providers this should be ok, because they're rejecting if there's no state.

What i've been "wanting" when implementing a more complex custom provider, is that it be configurable where possible if not good for defaults. Like if it was a simple whitelist "trigger on [`'`,`"`,`(`,`.`]", it could help because we can return nothing to dismiss the list, and return the same state to keep it open. 

Aside for the completion not showing at all (trigger), the inverse of that (the dismissal) is out of our control, making it impossible to cater to certain aspects of the language, but the majority of the pain points are not language specific that I've run into - though they will potentially be coder preference based (like typing function calls with `func( arg0 )` instead of `func(arg0)`.

**Comment by benogle** [comment]
> Like if it was a simple whitelist "trigger on [',",(,.]"

We can just trigger on nearly everything, and allow the provider to make the decision. I dont think we need another option. There is now a [`prefixRegex`](https://github.com/atom-community/autocomplete-plus/blob/c53ec2424dd38d01468c909c2af353b017c21a5c/lib/autocomplete-manager.coffee#L31) that has all the trigger chars.

**Comment by underscorediscovery** [comment]
That's great, that's plenty configurable I think!

**Comment by acormier** [comment]
That's great!  Thanks.
