### ISSUE TITLE
Disable suggestions after semicolons.

### ISSUE THREAD

**Issue by andrewhathaway** [atom-community/autocomplete-plus#273]
Couldn't find anything on this but its starting to bug me a little. When finishing a line with a semicolon, Autocomplete+ suggests another entry and when pressing the enter key, adds it in to the line. However as I've just finished my line, it shouldn't be suggesting and I should be pressing enter to return on to a new line.

![image](https://cloud.githubusercontent.com/assets/1188830/6279470/c4e9c1d4-b899-11e4-9700-2b9a9f5b12bd.png)

Not sure if the above description is descriptive or correctly worded but in the screenshot attached it shows that its trying to suggest after a semicolon and pressing the enter key will result in the variable "x" being added to the line and not returning on the next line.

Any help is greatly appreciated, thanks.

**Comment by benogle** [comment]
Hey, this is because the fuzzy provider shows suggestions for no prefix. [this](https://github.com/atom-community/autocomplete-plus/blob/master/lib/fuzzy-provider.coffee#L60) is misleading because in your case, the prefix is `;`. 

Though my suggestion would be to make sure the fuzzyProvider only show suggestions who's first char matches the first char of the prefix. That could be done [here](https://github.com/atom-community/autocomplete-plus/blob/master/lib/fuzzy-provider.coffee#L148). 

The easiest thing, though, for now, would be to switch the default provider to the `Symbol` Provider in the settings (the last option).

**Comment by josebalius** [comment]
@benogle I am running into the same problem :/ my default provider is Symbol as stated above but I keep getting suggestions after `;` which is really irritating. Using Atom 1.0 and autocomplete-plus 2.19.0. Any suggestions?

**Comment by benogle** [comment]
@josebalius What kind of file are you in? What atom version specifically? Make sure you are up to atom 1.0.3. In 1.0.4 there will be a fix for css completions being too eager.

**Comment by jacobfike** [comment]
This issue has started happening again, recently.  After typing a semicolon, I get a huge list of suggestions.  This is not helpful and makes is very frustrating when trying to hit enter to go to the next line after obviously finishing a line with a semicolon.

![image](https://user-images.githubusercontent.com/254671/48090772-ad284980-e1bc-11e8-953b-fc2fb8d60377.png)

**Comment by thomasjo** [comment]
@jacobfike This issue was resolved over 3 years ago. Please open a new issue.
