### ISSUE TITLE
Weird behaviour when autocompleting with dashes 

### ISSUE THREAD

**Issue by javve** [atom-community/autocomplete-plus#287]
Example:
I have a css-class named `computer-screen-section` and if I type *computer-scre* and then use the autocomplete the completed class name becomes `computer-computer-screen-section`.

Can I fix this with I setting or something? :confused:

**Comment by benogle** [comment]
This is the perfect storm between The FuzzyProvider and the wordRegex not supporting dashes. What happens is this

* type `computer` and it matches __computer__-screen-section
* type `computer-sc` and it matches computer-**sc**reen-section 

The wordRegex used to generated prefixes doesnt handle dashes, so `sc` is the prefix it's searching for, and FuzzyProvider matches the prefix in the middle of a word. 

You can use the `Symbol` provider as the default provider, but it will no longer match after you type `computer-sc` because the prefix wordRegex bug is still there.

**Comment by nikolaydyankov** [comment]
+1
