### ISSUE TITLE
Undefined, Undefined, Undefined, Undefined, Undefined, Undefined, 

### ISSUE THREAD

**Issue by yadunand-haxa** [atom-community/autocomplete-plus#298]
![screen shot 2015-03-01 at 3 33 47 pm](https://cloud.githubusercontent.com/assets/8816761/6429869/85693a62-c028-11e4-8de8-0e00bdcc2af9.png)

**Comment by lierdakil** [comment]
I think this happens when provider returns matches with `prefix` not contained in `word`, e.g.
![atom-ac-plus-much-undefined](https://cloud.githubusercontent.com/assets/7275622/6431221/ba46e660-c039-11e4-880d-6a338cc02f1a.png)

I'll try to pinpoint the location. Most likely, it's highlighting issue.

**Comment by benogle** [comment]
Sorry about this, it's out in 2.3.1.
