### ISSUE TITLE
Autocompletion opens on space

### ISSUE THREAD

**Issue by iraasta** [atom-community/autocomplete-plus#341]
I don't know if that's desired behaviour

But my autocompletion dialog displays on space input and many other non-word characters like parenthesis and brackets.

Is it by design or is it some bug in one of my packages?

Best regards,
Chris

**Comment by benogle** [comment]
Can you try upgrading to 2.7.0 and report back? There are several improvements to the default provider, and it should not open on space anymore.

**Comment by philk** [comment]
I'm still seeing this on 2.7.0 (and was before, not sure when it started happening)

You can't really see my cursor in this screenshot but it's right after I type the comma that the autocomplete window pops up. Annoying mainly because I so often want to hit enter to go to the next line right after typing a comma (instead I get an arbitrary autocomplete). I'm on go-plus 3.3.1 with the `Suppress Built-In Autocomplete Plus Provider` option turned on if that has any influence.

![screen shot 2015-03-26 at 3 25 42 pm](https://cloud.githubusercontent.com/assets/29562/6858518/6f3bd1e8-d3cc-11e4-849f-4d00d5e33448.png)

**Comment by benogle** [comment]
@philk your issue is a bug with the go provider. Can you open an issue on that repo?

**Comment by philk** [comment]
Ah cool, seemed similar. Will do, thanks.

**Comment by iraasta** [comment]
Yup. It fixed it.
Great job guys!
Now my Erlang and Elixir providers work like a charm! :D
By the way. What is the requirement to be add to the providers list?

Cheers

**Comment by benogle** [comment]
> Ah cool, seemed similar. Will do, thanks.

It was a change recently, providers now get notified of a space, but the provider needs to decide what to do in the case of a space. Spaces just probably arent handled in the go provider.

> By the way. What is the requirement to be add to the providers list?

You mean the wiki page? Or something else? If the wiki page, you can add it I think (not sure of permissions)? If not, let me know and I will add the link.

**Comment by benogle** [comment]
Closing as this is fixed.
