### ISSUE TITLE
Accept new provider param to perform fuzzy sorting / filtering logic in core autocomplete package

### ISSUE THREAD

**Issue by benogle** [atom-community/autocomplete-plus#360]
Currently, each provider needs to come up with some fuzzy filtering / sorting scheme. It's pretty boilerplate in many cases, and can be error prone. It would be nice to provide a default sorting / filtering scheme providers can opt into for ease and consistency across providers.

### New `filterSuggestions` param

A new provider would set a new `filterSuggestions` param new param to true, then return all its suggestions every time.

```coffee
provider =
  filterSuggestions: true # new!
  getSuggestions: (options) =>
    [{text: 'ab'}, {text: 'abc'}, {text: 'abcd'}, {text: 'omg'}]
```

Filtering would happen in the core package. An algorithm that matches our current approach might look like the following:

```coffee
filterSuggestions: (suggestions, {prefix}) ->
  candidates = fuzzaldrin.filter(suggestions, prefix, key: 'text')

  # Dont show matches that are the same as the prefix.
  # And only show those that match the first char
  results = []
  lowercasePrefixChar = prefix[0].toLowerCase()
  for candidate in candidates when word isnt prefix
    continue unless lowercasePrefixChar is candidate.text[0].toLowerCase()
    results.push candidate
  results
```

**Comment by tinloaf** [comment]
Wouldn't that mean that a longer suggestion has a disadvantage compared to a shorter suggestion? For example:

```
> fuzzaldrin =  require('fuzzaldrin')
{ filter: [Function],
  score: [Function],
  match: [Function] }
> fuzzaldrin.score('abc', 'a')
0.12
> fuzzaldrin.score('abcd', 'a')
0.11249999999999999
```

In my opinion, typing 'a' does not mean that I'd rather want 'abc' than 'abcd'. It's even possible that way to prefer an invalid match over a valid one (but with a longer string):
```
> fuzzaldrin.score('abcdefghijklmnopqrstuvwxyz123456789', 'abc')
0.0977142857142857
> fuzzaldrin.score('acbc', 'abc')
0.1155
```
In this case, I'd probably prefer 'abcdefghijklmnopqrstuvwxyz123456789', right? It's just a really long method name.

So perhaps some other scoring mechanism than fuzzaldrin would be in order here? Or just match a prefix of the same length as the query?

**Comment by benogle** [comment]
> Wouldn't that mean that a longer suggestion has a disadvantage compared to a shorter suggestion?

Yeah, it seems that way. In practice it isnt so bad though. The default providers already use this, and it feels ok. Using fuzzaldrin is a good first implementation to allow providers to not think about filtering suggestions.

As a separate unit of work, we could improve the fuzzy filtering using a trie. Something like this: http://stevehanov.ca/blog/index.php?id=114

**Comment by jcdickinson** [comment]
@benogle I had a stab at this. I still have to figure out how to write the unit tests (as I'm new to CoffeeScript and Atom), but do you agree with the direction that I have headed?

https://github.com/jcdickinson/autocomplete-plus/commit/b292423a2c73a58c9cf1629f50b2c6d8558b7788

* Fixed a bug and addressed a fixme near to it. Providers cannot return the same (pointer) suggestion list multiple times without odd things happening. Use case: for clang this is an issue because calling out to clang is relatively expensive (so my plugin does 'things' and sometimes returns the same results).
* Another bug. The prefix is calculated when a provider is invoked. If the provider (specifically async) takes *longer* to execute than the user's keystroke the prefix is now out-of-date. It bubbles all the way through to the suggestion list and results in the bodification being multiple keystrokes behind.

https://github.com/jcdickinson/autocomplete-plus/commit/c5831e09dfef3c145bed806ae738101a2d50e296

* A provider can opt into filtering in one of two ways:
 * `filterSuggestions: true` - use the default filtering (implemented as you originally described)
 * `filterSuggesions: (suggestions, prefix) -> ...` - custom filtering function. This function is important for async providers as it receives the most recent prefix (as opposed to the potentially incorrect one as per the above commit)

https://github.com/jcdickinson/autocomplete-plus/commit/dd77b6359cd2b9767d5c8c028bfe7e237a18f025

* I figured out how to get the tests to run and fixed the regressions that I caused.

**Comment by benogle** [comment]
> jcdickinson@b292423

Not sure about this one. The replacementPrefix is separated from prefix so providers can supply their own prefix. Make a PR with just this one. 

> Another bug. 

Write a test case for this one.

> jcdickinson@c5831e0 & jcdickinson@dd77b63 

Make a separate PR with these two, and I will review it

**Comment by joefitzgerald** [comment]
@benogle wouldn't it be better to simply provide one or more filtering and / or sorting functions (perhaps aligned with differing strategies) to the providers? This could be via a serviceHub dependency, or could be provided in the options object.

I'm not entirely sure what was in @jcdickinson's code because his fork has disappeared.

**Comment by benogle** [comment]
Hey, I'm out the rest of the week and won't be able to spend any time on
autocomplete til Monday.
