### ISSUE TITLE
Need api: disable FuzzyProvider,  let typedText.length > 0

### ISSUE THREAD

**Issue by yongkangchen** [atom-community/autocomplete-plus#90]
> https://github.com/yongkangchen/atom-ctags/issues/3

1、I need a provider api to `disable just FuzzyProvider`
for reason is: atom-ctags auto update symbols when file save, there no need to enable FuzzyProvider. But still need autocomplete-snippets, so I can't use `exclusive` to exclusive all other provider. 

2、I need a provider api to let `typedText.length > 0` instead of `typedText.length is 1` in [autocomplete-view.coffee#L188](https://github.com/saschagehlich/autocomplete-plus/blob/master/lib/autocomplete-view.coffee#L188)
for reason is: when input `(`,  [bracket-matcher](https://github.com/atom/bracket-matcher) auto insert `)`, lead to `typedText.length == 2`, and I need autocomplete to show symbol for pre word which include function param.

**Comment by joefitzgerald** [comment]
@yongkangchen Would it suffice to simply ensure atom-ctags and autocomplete-snippets suggestions are always more specific (and consequently higher in priority) than FuzzyProvider?

**Comment by apcshields** [comment]
@joefitzgerald I'd like to be able to disable FuzzyProvider without disabling all other providers as well, but I'd specifically like the user to be able to decide to disable it or not.

With an earlier version of autocomplete-plus, I could simply use a fork of autocomplete-plus which had FuzzyProvider stripped out. That way the user could install autocomplete-plus or not, or adjust the individual fileBlacklist settings of the two autocomplete engines so that they didn't overlap. This doesn't seem possible anymore (without significant inconvenient rewriting), since providers are expected to use the atom.services api.

I'm chiming in here because I think it's important that however this issue is resolved, the user be in control. I think most of the users of my provider don't want to see the default provider options at all, but some may, and some may want to see them in some contexts but not in others. My solution wasn't optimal, but it let the user decide whether and when they would be presented with the different options. Now that I'm migrating back to the stock autocomplete-plus, I'd still like to provide my users with that same configurability.

**Comment by joefitzgerald** [comment]
:thumbsup: @apcshields: I'm going to provide two ways to suppress FuzzyProvider: 1) a preference to disable it entirely 2) a way for providers to add to a blacklist of selectors where the FuzzyProvider doesn't get used.

This provides flexibility for the user and provider authors.

**Comment by apcshields** [comment]
Great!
